name: junder (.exe)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Compilar o app (Build)
        run: npm run build

      - name: Criar Executável Windows
        run: |
          npx nativefier --name "MeuApp" "./dist" ./dist-app --single-instance

      - name: Disponibilizar download do .exe
        uses: actions/upload-artifact@v4
        with:
          name: claude-junder-EXE
          path: dist-app/
